apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dmo1lzkam-go 
  janus-idp.io/tekton: dmo1lzkam-go
  backstage.io/kubernetes-id: dmo1lzkam-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dmo1lzkam-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  