apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dmo1lzkam-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dmo1lzkam-go 
  name: dmo1lzkam-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dmo1lzkam-go 
